# Pull tomcat latest image from dockerhub 
From tomcat:latest

# Maintainer
MAINTAINER "ItResolveIt" 

# copy war file on to default location container 
COPY ./webapp.war /usr/local/tomcat/webapps
